<a href="https://colab.research.google.com/github/IgorNascAlves/Producao_hospitalar_no_brasil/blob/main/Nova_pasta2/primeira_analise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
URL = 'https://raw.githubusercontent.com/IgorNascAlves/Producao_hospitalar_no_brasil/main/Dados/interna%C3%A7%C3%B5es.csv'

In [ ]:
df = pd.read_csv(URL, encoding='ISO-8859-1', sep=';', skiprows=2, skipfooter=11, engine='python', header=1)
df.head()

  Unidade da Federação  2008/Jan  2008/Fev  ...  2021/Fev  2021/Mar    Total
0          11 Rondônia      4142      7301  ...      6463      6431  1387140
1              12 Acre      2087      3071  ...      3483      3969   637069
2          13 Amazonas      9325     12754  ...     17265     15855  2248754
3           14 Roraima      1475      1812  ...      3304      3278   465989
4              15 Pará     38628     41530  ...     34126     27721  6479075

[5 rows x 161 columns]